language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
